### ISSUE TITLE
Unclear behavior with pages <= 0

### ISSUE THREAD

**Issue by cbondurant** [EzraSkwarka/CYOA_Helper#49]
I found it confusing (though this is because Im a computer nerd) that `goto 0` did not give me the first pages of the books.

I then thought to try negative numbers to break it, `-1` seems to be some hard coded fake page and no page past -1 has any information. 

It would be helpful from a new-user experience perspective to have pages <= 0 print some prompting text along the lines of "That page doesnt make sense to me, did you mean {positive version of page number/ page one, if the player put 0}?" As it would give clearer intent about what kind of unexpected behavior is occurring. 

I dont think I can directly assign people at the moment so instead, @EzraSkwarka

**Comment by EzraSkwarka** [comment]
I will definitely take the "That page doesnt make sense to me" context-hint into consideration. But page 0 is actually the first page of the book for FF02, it has a preamble. I just mapped the pages from the source book directly. This is another point in the "I need to write up the instructions for building a book json file" camp.

**Comment by EzraSkwarka** [comment]
I added an echo message for when a given page number isn't reconized
